//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardGame.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardGame.Domain.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Enter] to play another game.
        /// </summary>
        public static string AnotherGame {
            get {
                return ResourceManager.GetString("AnotherGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Enter] to navigate home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Game.
        /// </summary>
        public static string CardGame {
            get {
                return ResourceManager.GetString("CardGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let the games begin.
        /// </summary>
        public static string InitPage {
            get {
                return ResourceManager.GetString("InitPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card color.
        /// </summary>
        public static string InvalidCardColor {
            get {
                return ResourceManager.GetString("InvalidCardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card id cannot be empty.
        /// </summary>
        public static string InvalidCardId {
            get {
                return ResourceManager.GetString("InvalidCardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card number.
        /// </summary>
        public static string InvalidCardNumber {
            get {
                return ResourceManager.GetString("InvalidCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid deck capacity.
        /// </summary>
        public static string InvalidDeckCapacity {
            get {
                return ResourceManager.GetString("InvalidDeckCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity cannot be less than the card maximum number. Kindly insert the new value..
        /// </summary>
        public static string InvalidDeckCapacityLessThenCardNumber {
            get {
                return ResourceManager.GetString("InvalidDeckCapacityLessThenCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There should be at least two players participating the game. The number of players should be even..
        /// </summary>
        public static string InvalidPlayerNumber {
            get {
                return ResourceManager.GetString("InvalidPlayerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press [Enter] to continue to the next round.
        /// </summary>
        public static string NextRound {
            get {
                return ResourceManager.GetString("NextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll the dice.
        /// </summary>
        public static string PlayPage {
            get {
                return ResourceManager.GetString("PlayPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to commence the game? (Y/N).
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string TitlePage {
            get {
                return ResourceManager.GetString("TitlePage", resourceCulture);
            }
        }
    }
}
